name: API State Tests
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/api-state-tests.yml'
jobs:
  test_bootstrap_1:
    name: bootstrap tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Install api libraries
        working-directory: ./api/source
        run: npm ci
      - name: Install Test dependencies
        working-directory: ./test/state
        run: npm ci
      - name: Print environment variables
        run: env
      - name: Print PATHs
        run: which node; which docker; which python3
      - name: Run tests
        working-directory: ./test/state
        run: ./node_modules/mocha/bin/mocha.js --reporter mochawesome --showFailed --exit './mocha/**/*.test.js'
      - name: Upload mocha test report
        id: artifact-upload-mocha
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: mocha-report
          path: ./test/state/mochawesome-report

