name: API State Tests
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/api-state-tests.yml'
jobs:
  test_bootstrap_1:
    name: Boot - without deps
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Install api libraries
        working-directory: ./api/source
        run: npm ci
      - name: Install Test dependencies
        working-directory: ./test/state
        run: npm ci
      - name: Run tests
        working-directory: ./test/state
        run: npm test

