name: Build client
on:
  workflow_dispatch:
  workflow_call:
jobs:
  builder:
    name: builder
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Install uglify-js
        run: npm install -g uglify-js
      - name: Create distribution
        working-directory: ./client
        run: ./build.sh
      - name: Upload distribution
        uses: actions/upload-artifact@v3
        with:
          name: client-dist
          path: ./client/dist
