name: Publish Docker images
on:
  workflow_dispatch:
  workflow_call:
jobs:
  build-client:
    name: Build client
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Install uglify-js
        run: npm install -g uglify-js
      - name: Create distribution
        working-directory: ./client
        run: ./build.sh
      - name: Upload distribution
        uses: actions/upload-artifact@v2
        with:
          name: clientDist
          path: ./client/dist
      

