name: Build docs
on:
  workflow_dispatch:
  workflow_call:
jobs:
  builder:
    name: builder
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: run image, generating docs
        working-directory: ./docs
        run: ./build.sh
      - name: Upload docs
        uses: actions/upload-artifact@v3
        with:
          name: docs-build
          path: ./docs/_build/html
